import { MOVIES, SIDEBAR } from "../constants/index";

const SEARCH = MOVIES.SEARCH;
const PAGE_LIST = MOVIES.PAGE_LIST;
const FETCH = MOVIES.FETCHING;
const FETCH_INFO = MOVIES.FETCH_INFO;
const FETCH_FAILURE = MOVIES.FETCH_FAILURE;
const FILTER_MOVIES = MOVIES.FILTER_MOVIES;
const MOVIE_GENRES = MOVIES.MOVIE_GENRES;
const TOGGLE_SIDEBAR = SIDEBAR.TOGGLE_SIDEBAR;

export {
  SEARCH,
  TOGGLE_SIDEBAR,
  FILTER_MOVIES,
  PAGE_LIST,
  FETCH,
  MOVIE_GENRES,
  FETCH_INFO,
  FETCH_FAILURE
};
