import { MOVIES } from "../constants/index";

const SEARCH = MOVIES.SEARCH;
const PAGE_LIST = MOVIES.PAGE_LIST;
const FETCH = MOVIES.FETCHING;
const FETCH_INFO = MOVIES.FETCH_INFO;
const FETCH_FAILURE = MOVIES.FETCH_FAILURE;
const FILTER_MOVIES = MOVIES.FILTER_MOVIES;
export { SEARCH, FILTER_MOVIES, PAGE_LIST, FETCH, FETCH_INFO, FETCH_FAILURE };
